default_platform(:ios)

import "Utils/Keychain.rb"
import "Utils/Git.rb"
import "Utils/Slack.rb"
import "Utils/Env.rb"
import "Lanes/Release.rb"
import "Lanes/Testflight.rb"

platform :ios do
  override_lane :release do      
  end
  override_lane :closed_beta do      
  end
end