default_platform(:ios)

import "Utils/Keychain.rb"
import "Utils/Git.rb"
import "Utils/Slack.rb"
import "Utils/Env.rb"
import "Lanes/Release.rb"
import "Lanes/Testflight.rb"

platform :ios do
 
  # Release
  lane :release do | params |  
    
    begin
      
      if !params[:bump]
        puts "No bump type defined! Use one of: patch | minor | major".red
        UI.user_error!("No bump type defined! Use one of: patch | minor | major".red)
      end
    
      private_release bump: params[:bump]

    rescue => exception
      on_error(exception)
    end

  end

  # Beta
  lane :beta do 
    private_beta     
  end

end