DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_API_KEY_CONTENT = ENV["APPLE_API_KEY_CONTENT"]
SLACK_CHANNEL = ENV["SLACK_CHANNEL"] 
GIT_USER = ENV["GIT_USER"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

APP_NAME = "CDProject"
SCHEME = "CDProject"